name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Capacitor
        run: |
          npm install @capacitor/core @capacitor/cli @capacitor/android

      - name: Create package.json
        run: |
          echo '{
            "name":"sonix",
            "version":"1.0.0"
          }' > package.json

      - name: Init Capacitor
        run: |
          npx cap init "SoniX Esports" "com.sonix.esports" --web-dir=.

      - name: Add Android
        run: npx cap add android

      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: sonix-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
